### ISSUE TITLE
(HIGH) Phinx

### ISSUE THREAD

**Issue by wolfy-j** [spiral/spiral#106]

**Comment by wolfy-j** [comment]
Or restore spiral migration engine.

**Comment by wolfy-j** [comment]
Also i need bridge for Doctrine as Data Mapper alternative.

**Comment by sidz** [comment]
I think you can use phinx for this. I tried this migration tool on the one of my old cakePHP project. ;)

**Comment by wolfy-j** [comment]
Thx, since i already have embedded schema generator it's not critical, but manually controlled migrations are must have.

**Comment by wolfy-j** [comment]
https://www.youtube.com/watch?v=6KCYBei7H6Q&feature=share

**Comment by sidz** [comment]
:+1:
