### ISSUE TITLE
Enhancements to create:command

### ISSUE THREAD

**Issue by adelowo** [spiral/spiral#179]
Hi, I have been trying to take a look at the framework and i wanted to test drive the console integration.

I ran `./spiral create:command SampleCommand` .. but it creates a Command file called `SampleCommandCommand`.. The `create:command` can be improved to check if the argument passed (command name) has it's suffix as "Command". If yes, don't prepend "Command" to the name and leave it as is. If no, prepend "Command" to the file name.

I would have loved to fix it but i just started ___poking___ into the code-base (which is quite large)..

**Comment by wolfy-j** [comment]
Hi,

class postfix automatically added based on your scaffolder config located in "app/config/modules/scaffolder", you can skip postfix for your classes. \

Though, if you think that automatic postfix generation creates issues we can alter this class of scaffolder module: 

https://github.com/spiral-modules/scaffolder/blob/master/source/Scaffolder/Configs/ScaffolderConfig.php#L65

**Comment by wolfy-j** [comment]
In this case, it will properly detect and skip postfixes for all class declarations.

**Comment by wolfy-j** [comment]
Scaffolder configuration: https://github.com/spiral/application/blob/develop/app/config/modules/scaffolder.php

**Comment by adelowo** [comment]
Oh, easy catch, i like the idea of the postfix.. I don't think it would cause any issues, it's all my fault since i didn't read the documentation properly (or looked into the configuration)..

So i can just run `./spiral create:command Sample` and i get `SampleCommand`.. Cool

**Comment by wolfy-j** [comment]
You should also be able to include custom namespaces `./spiral create:command sample/test" => `Commands\Sample\TestCommand`
