### ISSUE TITLE
[Validation package] Don't validate the same data set twice (details inside)

### ISSUE THREAD

**Issue by adelowo** [spiral/spiral#180]
`validate` is called in `getErrors`  [here](https://github.com/spiral/spiral/blob/develop/source/Spiral/Validation/Validator.php#L206) and `isValid` [here](https://github.com/spiral/spiral/blob/develop/source/Spiral/Validation/Validator.php#L168). 

The goal is to remove code duplication..  Both `isValid` and `getErrors` calls the validate method before returning a response to the caller.. This leads to performing the same chore twice. 

For instance, say i call `isValid` (validation runs here), if i get a falsy value, i obviously would want to call `getErrors` to show the user who went wrong. On calling getErrors,the data is re-validated before the errors are returned.

**Comment by adelowo** [comment]
Kind of related --- > 

I also think the `validate` method should be exposed on the `ValidatorInterface`[here](https://github.com/spiral/spiral/blob/develop/source/Spiral/Validation/ValidatorInterface.php) as it should lead to better usability (since it actual does the validation not `isValid`.... I tried working on this (issue) but the tests are broken, while i have fixed most, i have hit a stumbling block with the `ValidatesEntity`

**Comment by wolfy-j** [comment]
Fair point, we had error cache in 0.8 version, but due refactoring this micro-optimization is gone. I'll take a look if test suite ready to handle this change.

**Comment by adelowo** [comment]
I don't think the test suite is ready for that.. I did it and everything got broken..

Like i said earlier, i am still yet to fix the tests for `ValidatesEntity`

**Comment by adelowo** [comment]
I would have to wait for you to check this before i continue working on this issue

**Comment by wolfy-j** [comment]
Yes, i will take care of it next week after holidays. :)

**Comment by wolfy-j** [comment]
The trick here is to properly invalidate cache for validation errors.

**Comment by adelowo** [comment]
Oh, I would take a look at this tomorrow (or this night if am chanced) again

**Comment by adelowo** [comment]
The tests are still broken even after merging `feature/validate-entity` and exposing the 1Validate` method.. `ValidatesEntityTest` is the real culprit here...

Would look into this properly tomorrow.

**Comment by wolfy-j** [comment]
I can handle it i think, but only after weekends :)

**Comment by adelowo** [comment]
Alright then

**Comment by wolfy-j** [comment]
see #183
