### ISSUE TITLE
[HTTP Package] How to map routes to specific HTTP request method

### ISSUE THREAD

**Issue by adelowo** [spiral/spiral#185]
I don't seem to get this.. I don't seem to see how to make a route respond to a specific HTTP method, https://spiral-framework.com/guide/http-routing

I created a sample route... `POST` and `GET` seemed to work... In my sample app, I created middleware for this (`GetMiddleware`, `PostMiddleware`) but this is something that should work out of this box.

> I understand i can make use of another router though

**Comment by wolfy-j** [comment]
Hi, we are trying do not use same URLs for different actions based on method and this is not support on routing level.

Though, take a look at RESTFulCore (i think we did not document it):
https://github.com/spiral/spiral/blob/develop/tests/Http/RESTfulCoreTest.php

$route = $route->withCore(RESTfulCore::class);

I will allow you to use your controller methods in relation to HTTP method.

**Comment by wolfy-j** [comment]
I will create some docs for restful core :)
