### ISSUE TITLE
Reading source and I can't seem to find the \Spiral\Core\Component location?

### ISSUE THREAD

**Issue by exts** [spiral/spiral#195]
Just browsing source to see how spiral works and all that jazz, but I came across a class that doesn't seem to exists?

Am I going crazy? https://github.com/spiral/spiral/tree/develop/source/Spiral/Core

**Comment by wolfy-j** [comment]
Hi, please take a look here: https://github.com/spiral/common

**Comment by exts** [comment]
Oh god, thank you. I was losing my mind for a second. You have a wonderful looking framework btw.

**Comment by wolfy-j** [comment]
Thank you, FYI Component is being soft deprecated in a next version in order to improve decoupling.

**Comment by exts** [comment]
Interesting. Also I found out about this framework from reddit's weekly thread, how come no one has talked about this framework much? Documentation seems complete, code is fully fledged,etc... it hits all the marks, but I've never heard of it until today.

**Comment by wolfy-j** [comment]
We are simply unable to dedicate time to marketing or community this year. There are a plenty of ideas based on our current experience (https://github.com/spiral/goridge one of them and we are planning to integrate it into future version). We are fully pledged to support and maintain Spiral for years (team of 25 engineers), but there is no budget/time for dedicated "community" leader yet. :(
