### ISSUE TITLE
Comparing to Laravel, what are key features of Spiral?

### ISSUE THREAD

**Issue by ptrofimov** [spiral/spiral#201]

**Comment by wolfy-j** [comment]
Native support of PSR-7, optimized for stateless executions (when framework kept in memory and only invoked for each request), ORM with strict schema definitions and automatic database scaffolding (same for ODM), ability to isolate data (ORM models) using virtual database partitions for later feature extraction. Ability to test application using mock database. Ability to generate databases dynamically using DBAL introspection and reflections. Embedded static analysis tools. IoC with autowiring and declarative services (just faster than closures).

Everything else is pretty much similar, but we don't have facades.

In 1.1.0 version Spiral will include hybrid application core written on Golang (up to 65x higher performance, see https://github.com/spiral/roadrunner).

**Comment by wolfy-j** [comment]
Let me know if you have any other questions.
